package org.example.controllers;

import org.apache.commons.lang3.StringUtils;

import javax.servlet.http.HttpServletRequest;
import java.util.Optional;

public class MockUtils {

    public static final String ADD_OPERATOR = "/add-operator";
    public static final String OPER = "oper";
    public static final String ADMIN_LABEL = "adminLabel";
    public static final String EL_TAR = "elTar";
    public static final String GAS_TAR = "gasTar";
    public static final String HEAT_TAR = "heatTar";
    public static final String ROLE = "role";
    public static final String ROLE_VALUE = "roleValue";
    public static final String OPERATOR_ADD_OPERATOR = "/operator/add-operator";
    public static final String REDIRECT_ADMIN_ADD_OPERATOR = "redirect:/admin/add-operator";
    public static final String REDIRECT_FOR_ALL = "redirect:/forAll";
    public static final String EDIT_OPERATOR_ID = "/edit-operator/{id}";
    public static final String ID = "id";
    public static final String ADMIN = "admin";
    public static final String OPERATOR_EDIT_OPERATOR = "/operator/edit-operator";
    public static final String EDIT_OPERATOR = "/edit-operator";
    public static final String ADMI = "admi";
    public static final String REDIRECT_ADMIN_ALL_ADMIN_OPERATORS = "redirect:/admin/allAdmin-operators";
    public static final String DELETE_ID = "/delete/{id}";
    public static final String ALL_ADMIN_OPERATORS = "/allAdmin-operators";
    public static final String OPER_DTO = "operDto";
    public static final String ALL_TARIFF_AD_LABEL = "/all-tariff/{adLabel}";
    public static final String AD_LABEL = "adLabel";
    public static final String ADD_TARIFF = "/add-tariff";
    public static final String VALUE = "value";
    public static final String NAME = "name";
    public static final String REDIRECT_FOR_ALL_INFO_OPERATOR_OPER_LABEL = "redirect:/forAll/info-operator?operLabel=";
    public static final String TARIFFS_ALL_TARIFFS = "/tariffs/all-tariffs";
    public static final String DELETE_TARIFF = "/deleteTariff";
    public static final String DELETE_EL_TAR_ID = "/deleteElTar/{id}";
    public static final String REDIRECT_FOR_ALL_EL_TAR = "redirect:/forAll/elTar";
    public static final String REDIRECT_FOR_ALL_GAS_TAR = "redirect:/forAll/gasTar";
    public static final String DELETE_GAS_TAR_ID = "/deleteGasTar/{id}";
    public static final String DELETE_HEAT_TAR_ID = "/deleteHeatTar/{id}";
    public static final String REDIRECT_FOR_ALL_HEAT_TAR = "redirect:/forAll/heatTar";
    public static final String EDIT_EL_TAR_ID = "/editElTar/{id}";
    public static final String CURRENT_USER_NAME = "currentUserName";
    public static final String ADMIN_ID = "adminId";
    public static final String TARIFFS_EDIT_EL_TAR = "/tariffs/edit-elTar";
    public static final String EDIT_EL_TAR = "/editElTar";
    public static final String EDIT_GAS_TAR_ID = "/editGasTar/{id}";
    public static final String TARIFFS_EDIT_GAS_TAR = "/tariffs/edit-gasTar";
    public static final String EDIT_GAS_TAR = "/editGasTar";
    public static final String EDIT_HEAT_TAR_ID = "/editHeatTar/{id}";
    public static final String TARIFFS_EDIT_HEAT_TAR = "/tariffs/edit-heatTar";
    public static final String ADD_TAR_VALUE = "/addTar/{value}";
    public static final String EDIT_HEAT_TAR = "/editHeatTar";
    public static final String TARIFFS_CREATE_TARIFF = "tariffs/create-tariff";
    public static final String TARR = "tarr";
    public static final String ADD_TAR = "/addTar";
    public static final String REDIRECT_FOR_ALL1 = "redirect:/forAll/";
    public static final String TAR = "Tar";
    public static final String CREATE_ADMIN = "/createAdmin";
    public static final String OPERATOR_CREATE_ADMIN = "/operator/create-admin";
    public static final String ADMIN_DTO = "adminDto";
    public static final String OPERATOR_ALL_ADMINS = "/operator/all-admins";
    public static final String ADMIN_LIST = "/adminList";
    public static final String ADMIN_ = "/admin";
    public static final String CONSUMER = "/consumer";
    public static final String PAGE_NUMBER = "pageNumber";
    public static final String SORT_FIELD = "sortField";
    public static final String SORT_DIR = "sortDir";
    public static final String CURRENT_PAGE = "currentPage";
    public static final String TOTAL_PAGES = "totalPages";
    public static final String TOTAL_ITEMS = "totalItems";
    public static final String REVERSE_SORT_DIR = "reverseSortDir";
    public static final String ASC = "asc";
    public static final String DESC = "desc";
    public static final String CONSUMER_DTO = "consumerDto";
    public static final String PAGE_NUMBER1 = "/{pageNumber}";
    public static final String CREATE_REPORT = "/createReport";
    public static final String MESSAGE = "message";
    public static final String MESSAGE1 = "Ваш оператор был удален. Дождитесь пока Вам назначать нового";
    public static final String REPORT_ERROR = "report/error";
    public static final String MESSAGE2 = "Ваш оператор еще не назначил Вам тарифы";
    public static final String MONTHS = "months";
    public static final String CONS = "cons";
    public static final String REPORT_CREATE_REPORT = "report/create-report";
    public static final String EL_VALUE = "elValue";
    public static final String GAS_VALUE = "gasValue";
    public static final String HEAT_VALUE = "heatValue";
    public static final String MON = "mon";
    public static final String YEAR = "year";
    public static final String REDIRECT_CONSUMER_CREATE_REPORT = "redirect:/consumer/createReport";
    public static final String ALL_REPORTS = "/allReports";
    public static final String CONS_ID = "consId";
    public static final String CONSUMER_ALL_CONSUMERS = "/consumer/all-consumers";
    public static final String REPORT_ALL_REPORT = "/report/all-report";
    public static final String ALL_REPORT = "/allReport";
    public static final String YEAR_1 = "year1";
    public static final String MESSAGE3 = "Ваш администратор еще не назначил вам тарифы";
    public static final String REP_LIST = "repList";
    public static final String EL_COST = "elCost";
    public static final String GAS_COST = "gasCost";
    public static final String HEAT_COST = "heatCost";
    public static final String EL_PAY = "elPay";
    public static final String GAS_PAY = "gasPay";
    public static final String HEAT_PAY = "heatPay";
    public static final String EL_COUNT = "elCount";
    public static final String GAS_COUNT = "gasCount";
    public static final String HEAT_COUNT = "heatCount";
    public static final String IS_PAID = "IsPaid";
    public static final String OPER_LABEL = "operLabel";
    public static final String MONTH = "month";
    public static final String TOTAL_PAYMENT = "totalPayment";
    public static final String INFO_OPERATOR = "/info-operator";
    public static final String FOR_ALL = "forAll";
    public static final String FLAG = "flag";
    public static final String CONSUMER1 = "consumer";
    public static final String OPERATOR1 = "operator";
    public static final String CON_WITH_OUT = "conWithOut";
    public static final String OPERATOR_INFO_OPERATOR = "/operator/info-operator";
    public static final String FIND_OPERATOR = "/find-operator";
    public static final String OPERATOR_FIND_OPERATOR = "/operator/find-operator";
    public static final String OPERATOR_ALL_OPERATORS = "/operator/all-operators";
    public static final String EL_TAR1 = "/elTar";
    public static final String TARIFFS_EL_TAR = "/tariffs/el-tar";
    public static final String GAS_TAR1 = "/gasTar";
    public static final String TARIFFS_GAS_TAR = "/tariffs/gas-tar";
    public static final String HEAT_TAR1 = "/heatTar";
    public static final String TARIFFS_HEAT_TAR = "/tariffs/heat-tar";
    public static final String OPER_ID = "operId";
    public static final String CONSUMER_CREATE_CONSUMER = "/consumer/create-consumer";
    public static final String ADD_CONSUMER = "/addConsumer";
    public static final String CREATE_CONSUMER = "/createConsumer";
    public static final String REDIRECT_OPERATOR = "redirect:/operator";
    public static final String EDIT_CONSUMER_ID = "/editConsumer/{id}";
    public static final String CONSUMER_EDIT_CONSUMER = "/consumer/edit-consumer";
    public static final String EDIT_CONSUMER = "/editConsumer";
    public static final String REDIRECT_OPERATOR_FIND_OP_CONS = "redirect:/operator/findOpCons";
    public static final String DELETE_CONSUMER_ID = "/deleteConsumer/{id}";
    public static final String FIND_CONS_INFO = "/findConsInfo";
    public static final String CONSUMER_FIND_CONSUMER = "/consumer/find-consumer";
    public static final String SHOW_ALL_FIND = "/showAllFind";
    public static final String CONS_NAME = "consName";
    public static final String CONS_SURNAME = "consSurname";
    public static final String GET_INFO_ID = "/getInfo/{id}";
    public static final String CONSUMER_INFO_CONSUMER = "/consumer/info-consumer";
    public static final String EDIT_REPORT_ID = "/editReport/{id}";
    public static final String REPORT_EDIT_REPORT = "/report/edit-report";
    public static final String REP = "rep";
    public static final String EDIT_REPORT = "/editReport";
    public static final String REDIRECT_OPERATOR_GET_INFO = "redirect:/operator/getInfo/";
    public static final String FIND_OP_CONS = "/findOpCons";
    public static final String CONSUMER_OPERATOR_CONSUMERS = "/consumer/operator-consumers";
    public static final String OPERATOR_ = "/operator";

    public static String getParam(HttpServletRequest req, String fieldName) {
        return Optional.ofNullable(req.getParameter(fieldName))
                .filter(StringUtils::isNotBlank)
                .orElse(null);
    }
}
